version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "178inaba"
  - package-ecosystem: "github-actions"
    directory: "/test-actions"
    schedule:
      interval: "daily"
    assignees:
      - "178inaba"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "178inaba"
