version: 2
updates:
  - package-ecosystem: docker-compose
    directory: /
    schedule:
      interval: daily
    assignees:
      - 178inaba
  - package-ecosystem: github-actions
    directories:
      - /
      - /test-actions
    schedule:
      interval: daily
    assignees:
      - 178inaba
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    assignees:
      - 178inaba
