version: "2"

linters:
  exclusions:
    presets:
      - std-error-handling

formatters:
  enable:
    - goimports
    - gci
  settings:
    goimports:
      local-prefixes:
        - github.com/178inaba/third-party-test
    gci:
      sections:
        - standard
        - default
        - blank
        - dot
        - alias
        - localmodule
