language: go

go:
  - 1.4
  - 1.5
  - tip

before_install:
  - go get -u -v github.com/axw/gocov/gocov
  - go get -u -v github.com/mattn/goveralls
  - if ! go get -u -v github.com/golang/tools/cmd/cover; then go get -u -v golang.org/x/tools/cmd/cover; fi

script:
  - $HOME/gopath/bin/goveralls
