services:
  lint:
    image: golangci/golangci-lint:v2.4.0
    entrypoint: ['golangci-lint', 'run']
    volumes:
      - .:/app
      - gomod-cache:/go/pkg/mod
      - lint-cache:/root/.cache
    working_dir: /app

volumes:
  gomod-cache:
  lint-cache:
