version: 2.1

references:
  test-steps: &test-steps
    steps:
      - checkout
      - restore_cache:
          name: Restore module caches
          keys:
            - go-modules-v1-{{ .Branch }}-{{ checksum "go.sum" }}
            - go-modules-v1-{{ .Branch }}-
            - go-modules-v1-
      - run:
          name: Test
          command: make -s test
      - save_cache:
          name: Save module caches
          key: go-modules-v1-{{ .Branch }}-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod

jobs:
  lint:
    machine:
      image: ubuntu-2404:current
    steps:
      - checkout
      - restore_cache:
          name: Restore module caches
          keys:
            - go-modules-v1-{{ .Branch }}-{{ checksum "go.sum" }}
            - go-modules-v1-{{ .Branch }}-
            - go-modules-v1-
      - run:
          name: Lint
          command: make -s lint
      - save_cache:
          name: Save module caches
          key: go-modules-v1-{{ .Branch }}-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod

  test-previous:
    docker:
      - image: cimg/go:1.24
    <<: *test-steps

  test-latest:
    docker:
      - image: cimg/go:1.25
    <<: *test-steps

workflows:
  test:
    jobs:
      - lint
      - test-latest
      - test-previous
