name: Lint and Test

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'github-actions[bot]' }}
    permissions:
      contents: write
    outputs:
      has_changes: ${{ steps.check-changes.outputs.has_changes }}
    steps:
      - name: Create GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.AUTO_FIX_BOT_APP_ID }}
          private-key: ${{ secrets.AUTO_FIX_BOT_PRIVATE_KEY }}
      - name: Get user id
        id: get-user-id
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: echo "user-id=$(gh api '/users/${{ steps.app-token.outputs.app-slug }}[bot]' --jq .id)" >> "${GITHUB_OUTPUT}"
      - name: Checkout
        uses: actions/checkout@v5
        with:
          token: ${{ steps.app-token.outputs.token }}
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Run go mod tidy
        run: make -s modtidy
      - name: Run modernize
        run: make -s modernize
      - name: Get golangci-lint version
        id: version
        run: |
          img_ref=$(cat compose.yaml | yq '.services.lint.image')
          echo "version=${img_ref#*:}" >> "${GITHUB_OUTPUT}"
      - name: GolangCI Lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: ${{ steps.version.outputs.version }}
          args: --fix
      - name: Check for changes
        id: check-changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then echo 'has_changes=true' >> "${GITHUB_OUTPUT}"; fi
      - name: Commit and push changes
        if: ${{ steps.check-changes.outputs.has_changes }}
        run: |
          git config user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
          git config user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'
          git add .
          git commit -m "Auto-fix: tidy, modernize, and lint

          - go mod tidy
          - modernize code
          - lint fixes"
          git push

  test:
    name: Test
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'github-actions[bot]' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - uses: ./.github/actions/test

  test-after-lint:
    name: Test After Lint
    runs-on: ubuntu-latest
    needs: lint
    if: ${{ needs.lint.outputs.has_changes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - uses: ./.github/actions/test
