name: Lint and Test

on: push

jobs:
  lint:
    name: Lint ${{ matrix.go }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.14', '1.15' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Install lint tools
        run: make -s go-get-tools
      - name: Run Gofmt diff
        run: make -s fmt-diff
      - name: Run Golint
        run: make -s lint
      - name: Run Vet
        run: make -s vet

  golangci-lint:
    name: GolangCI Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: GolangCI Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.31

  test:
    name: Test ${{ matrix.go }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.14', '1.15' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Test
        run: make -s test
